In [10]:
import numpy as np

In [41]:
vectors = np.array(
    [[0,0,4],
     [0,1,1],
     [1,1,1]]
)

In [21]:
q1 =vectors[0]

In [22]:
#creating unit vector - dividing vector by norm gives the unit vector
q1_normalized = q1/np.linalg.norm(q1)
q1_normalized

array([0., 0., 1.])

In [23]:
#putting it in al list
basis = []
basis.append(q1_normalized)

In [24]:
q2 = vectors[1] - np.dot(q1_normalized, vectors[1]) * q1_normalized
if np.linalg.norm(q2) < 1e-7:
    print("q2 is dependent on q1")
else: 
    q2_normalized =q2/np.linalg.norm(q2)
    basis.append(q2_normalized)
    q2_normalized

In [25]:
basis

[array([0., 0., 1.]), array([0., 1., 0.])]

In [26]:
q2_normalized

array([0., 1., 0.])

In [27]:
q3 = vectors[2] - \
    np.dot(q1_normalized, vectors[1]) * q1_normalized - \
    np.dot(q2_normalized, vectors[1]) * q2_normalized
if np.linalg.norm(q3) < 1e-7:
    print("q3 is dependent on q1 and/or q2")
else: 
    q3_normalized =q3/np.linalg.norm(q3)
    basis.append(q3_normalized)
    q3_normalized

In [28]:
basis

[array([0., 0., 1.]), array([0., 1., 0.]), array([1., 0., 0.])]

In [ ]:
#find the comp of q4 which is orto to q1 and q3 only

In [42]:
def gram_schmidt(vectors):
    basis = []
    for ai in vectors:
        qnew = ai - np.sum(np.dot(ai,qj) * qj for qj in basis)
        norm = np.linalg.norm(qnew)
        if (norm>1e-10):
            basis.append(qnew/norm)
        else:
            raise Exception(f'vector {ai} is linearly dependent on other')

    return np.array(basis)

In [43]:
gram_schmidt(vectors)

C:\Users\MSIS\AppData\Local\Temp\ipykernel_9588\4178146726.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  qnew = ai - np.sum(np.dot(ai,qj) * qj for qj in basis)


array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [44]:
vectors = np.array(
    [[0,0,4],
     [0,0,2],
     [1,1,1]]
)
gram_schmidt(vectors)

C:\Users\MSIS\AppData\Local\Temp\ipykernel_9588\4178146726.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  qnew = ai - np.sum(np.dot(ai,qj) * qj for qj in basis)


Exception: vector [0 0 2] is linearly dependent on other